version: "3.3"
services:
  eureka-server:
    build: ./eureka-server
    restart: on-failure
    depends_on:
      - config-server
    ports:
      - "8761:8761"
      - "8762:8762"
    environment:
      - JAVA_OPTIONS=-server -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/yuuyoo/ -Duser.timezone=Asia/Shanghai
      #- CONFIG_SERVER_URL=http://config-server:8888
    networks:
      - yuuyoo-dev
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
      - "8887:8887"
    volumes:
      # 替换成本地config-repo仓库地址
      - "${configRepo}:/config-repo"
    environment:
      - JAVA_OPTIONS=-server -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/yuuyoo/ -Duser.timezone=Asia/Shanghai
      - spring.rabbitmq.addresses=rabbit:5672
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
    networks:
      - yuuyoo-dev
  mongo:
    image: mongo:3.4.10
    ports:
      - "27017:27017"
    networks:
      - yuuyoo-dev
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:3.2-alpine
    networks:
      - yuuyoo-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  rabbit:
    build: ./rabbitmq
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    networks:
      - yuuyoo-dev
    environment:
      - RABBITMQ_DEFAULT_VHOST=yuuyoo

networks:
  yuuyoo-dev:
    driver: bridge

volumes:
  redis_data:
  mongo_data:
